name: Lint
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - name: Check out code
      - uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config ./.golangci.yml